# Generated by Django 5.2.3 on 2025-06-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_insercao', models.DateField()),
                ('uso_diario_horas', models.FloatField()),
                ('descanso_diario_horas', models.FloatField()),
                ('tipo_uso', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('pesado', 'Pesado')], max_length=10)),
                ('vida_util_estimativa', models.FloatField(help_text='Em dias')),
            ],
        ),
    ]
