# Generated by Django 5.2.3 on 2025-06-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peca',
            old_name='uso_diario_horas',
            new_name='descanso_diario',
        ),
        migrations.RenameField(
            model_name='peca',
            old_name='descanso_diario_horas',
            new_name='uso_diario',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='tipo_uso',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='vida_util_estimativa',
        ),
        migrations.AddField(
            model_name='peca',
            name='vida_util_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
