# Generated by Django 5.2.3 on 2025-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0002_rename_uso_diario_horas_peca_descanso_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='vida_util_total',
            field=models.IntegerField(default=0),
        ),
    ]
