# Generated by Django 5.2.3 on 2025-06-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0003_alter_peca_vida_util_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(choices=[('parafuso', 'Parafuso'), ('correia', 'Correia'), ('ventosa', 'Ventosa')], max_length=50)),
                ('data_troca', models.DateField()),
                ('data_quebra', models.DateField()),
                ('tempo_uso_diario', models.FloatField()),
                ('intensidade_uso', models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=20)),
            ],
        ),
    ]
