# Generated by Django 5.2.3 on 2025-06-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0004_historicopeca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='vida_util_total',
        ),
        migrations.AddField(
            model_name='historicopeca',
            name='descanso_diario',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicopeca',
            name='vida_util_restante',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicopeca',
            name='intensidade_uso',
            field=models.CharField(choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicopeca',
            name='peca',
            field=models.CharField(choices=[('parafuso', 'Parafuso'), ('correia', 'Correia'), ('ventosa', 'Ventosa')], max_length=20),
        ),
    ]
