# Generated by Django 5.2.3 on 2025-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manutencao', '0005_remove_peca_vida_util_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicopeca',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('melhoria', 'Melhoria/Upgrade')], default='corretiva', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicopeca',
            name='intensidade_uso',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=10, null=True),
        ),
    ]
